import { normalizeText } from "./format.js";

const REGION_ALIASES: Record<string, string> = {
  andalucia: "Andalucia, Extremadura y Canarias",
  extremadura: "Andalucia, Extremadura y Canarias",
  canarias: "Andalucia, Extremadura y Canarias",
  almeria: "Andalucia, Extremadura y Canarias",
  almería: "Andalucia, Extremadura y Canarias",
  cadiz: "Andalucia, Extremadura y Canarias",
  cádiz: "Andalucia, Extremadura y Canarias",
  cordoba: "Andalucia, Extremadura y Canarias",
  córdoba: "Andalucia, Extremadura y Canarias",
  granada: "Andalucia, Extremadura y Canarias",
  huelva: "Andalucia, Extremadura y Canarias",
  jaen: "Andalucia, Extremadura y Canarias",
  jaén: "Andalucia, Extremadura y Canarias",
  malaga: "Andalucia, Extremadura y Canarias",
  málaga: "Andalucia, Extremadura y Canarias",
  sevilla: "Andalucia, Extremadura y Canarias",
  badajoz: "Andalucia, Extremadura y Canarias",
  caceres: "Andalucia, Extremadura y Canarias",
  cáceres: "Andalucia, Extremadura y Canarias",
  tenerife: "Andalucia, Extremadura y Canarias",
  "santa cruz de tenerife": "Andalucia, Extremadura y Canarias",
  "las palmas": "Andalucia, Extremadura y Canarias",
  centro: "Centro y Castilla La Mancha",
  "castilla la mancha": "Centro y Castilla La Mancha",
  madrid: "Centro y Castilla La Mancha",
  getafe: "Centro y Castilla La Mancha",
  toledo: "Centro y Castilla La Mancha",
  guadalajara: "Centro y Castilla La Mancha",
  cuenca: "Centro y Castilla La Mancha",
  albacete: "Centro y Castilla La Mancha",
  "ciudad real": "Centro y Castilla La Mancha",
  levante: "Levante, Cataluña, Pais Vasco",
  cataluna: "Levante, Cataluña, Pais Vasco",
  cataluña: "Levante, Cataluña, Pais Vasco",
  "pais vasco": "Levante, Cataluña, Pais Vasco",
  barcelona: "Levante, Cataluña, Pais Vasco",
  girona: "Levante, Cataluña, Pais Vasco",
  gerona: "Levante, Cataluña, Pais Vasco",
  lleida: "Levante, Cataluña, Pais Vasco",
  lerida: "Levante, Cataluña, Pais Vasco",
  tarragona: "Levante, Cataluña, Pais Vasco",
  valencia: "Levante, Cataluña, Pais Vasco",
  alicante: "Levante, Cataluña, Pais Vasco",
  castellon: "Levante, Cataluña, Pais Vasco",
  castellón: "Levante, Cataluña, Pais Vasco",
  murcia: "Levante, Cataluña, Pais Vasco",
  bizkaia: "Levante, Cataluña, Pais Vasco",
  vizcaya: "Levante, Cataluña, Pais Vasco",
  gipuzkoa: "Levante, Cataluña, Pais Vasco",
  guipuzcoa: "Levante, Cataluña, Pais Vasco",
  alava: "Levante, Cataluña, Pais Vasco",
  álava: "Levante, Cataluña, Pais Vasco",
  arava: "Levante, Cataluña, Pais Vasco",
  araba: "Levante, Cataluña, Pais Vasco"
};

export function resolveRegionAlias(input: string) {
  const normalized = normalizeText(input);
  return REGION_ALIASES[normalized];
}
